"""initial

Revision ID: 25900b233474
Revises: 
Create Date: 2026-06-02 08:06:28.250885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25900b233474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('User', 'Author', 'Moderator', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('source_app', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'on_moderation', 'published', 'rejected', name='experience_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_status'), ['status'], unique=False)

    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journey_type', sa.Enum('experience', 'route', name='journey_type'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', name='journey_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journeys_user_id'), ['user_id'], unique=False)

    op.create_table('personal_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='route_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_routes_owner_id'), ['owner_id'], unique=False)

    op.create_table('experience_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_points_experience_id'), ['experience_id'], unique=False)

    op.create_table('journey_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journey_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_progress_journey_id'), ['journey_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending', 'paid', 'failed', 'refunded', name='order_status'), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_provider_event_id'), ['provider_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('experience', 'route', name='review_target_type'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('route_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['personal_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_points_route_id'), ['route_id'], unique=False)

    op.create_table('purchase_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_access_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_access_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_access_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_access_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_access_experience_id'))

    op.drop_table('purchase_access')
    with op.batch_alter_table('route_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_points_route_id'))

    op.drop_table('route_points')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_target_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_provider_event_id'))
        batch_op.drop_index(batch_op.f('ix_orders_experience_id'))

    op.drop_table('orders')
    with op.batch_alter_table('journey_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_progress_journey_id'))

    op.drop_table('journey_progress')
    with op.batch_alter_table('experience_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_points_experience_id'))

    op.drop_table('experience_points')
    with op.batch_alter_table('personal_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_routes_owner_id'))

    op.drop_table('personal_routes')
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_user_id'))

    op.drop_table('journeys')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_status'))
        batch_op.drop_index(batch_op.f('ix_experiences_city'))
        batch_op.drop_index(batch_op.f('ix_experiences_author_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
